ids: 
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Padrão");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Allip");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Carneçal");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Carniçal");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Centopéia Imensa");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Demônio");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Elemental do Ar (Pequeno)");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Enxame (centopéias)");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Esqueletos");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Esqueleto (Humano Combatente)");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Esqueleto (Lobo)");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Esqueleto (Troll)");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Gigante da Colina");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Grifo");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Hipogrifo");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Manto Negro");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Mephit do Fogo");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Humanos");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Humano Clérigo");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Humano Guerreiro");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Humano Ladino");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Humano Mago");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Humano Paladino");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Goblin");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Homem-Rato");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Ogro");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Ogro Bárbaro");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Orcs");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Orc");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Orc Lanceiro");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Orc Sargento");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Orc Tenente");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Orc Capitão");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Troll");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Uivante");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Zumbis");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Zumbi (humano)");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Zumbi (kobold)");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Worg");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Formas");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Árvore (genérica)");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Árvore (pinheiro)");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Árvore (seca)");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Casa (8x7)");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Moedas");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Baú (madeira)");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Barras");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Teste");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "teste orc");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "teste geo");
textos: 
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Babau");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Vrock");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Dretch");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Bebilith");
QT_TRANSLATE_NOOP("ifg::qt::MenuPrincipal", "Súcubo");
