load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
  name = "matrix",
  srcs = [
    "matrices.cpp",
  ],
  hdrs = [
    "matrices.h",
    "vectors.h",
  ],
  copts = [],
  deps = [
  ]
)
