package(default_visibility = ["//visibility:public"])

cc_library(
  name = "m3d",
  hdrs = [
    "m3d.h",
  ],
  srcs = [
    "m3d.cpp",
  ],
  copts = [],
  deps = [
    "//arq:arq",
    "//ent:ent_headers",
  ]
)
