package(default_visibility = ["//visibility:public"])

cc_library(
  name = "ifg_qt_ui",
  srcs = [
  ],
  hdrs = [
    "cenario.h",
    "dialogobonus.h",
    "entidade.h",
    "entradastring.h",
    "forma.h",
    "listapaginada.h",
    "opcoes.h",
  ],
  copts = [],
  deps = [
      "@qt//:qt_core",
      "@qt//:qt_widgets",
      "@qt//:qt_opengl",
  ]
)


