all:
	uic entidade.ui -o entidade.h
	uic por_origem.ui -o por_origem.h
	uic bonus_individual.ui -o bonus_individual.h
	uic opcoes.ui -o opcoes.h
	uic cenario.ui -o cenario.h
	uic forma.ui -o forma.h
	uic listapaginada.ui -o listapaginada.h
	uic entradastring.ui -o entradastring.h
	uic dialogo_bonus.ui -o dialogobonus.h

clean:
	rm *.h
